<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage.Master" AutoEventWireup="true" CodeBehind="userInfo.aspx.cs" Inherits="DDbook.userInfo" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <link rel="stylesheet" href="./css/userInfo.css">
</asp:Content>
<%--<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server"> 
</asp:Content>--%>
<asp:Content ID="Content3" ContentPlaceHolderID="ContentPlaceHolder2" runat="server">
    <nav>
            <ul>
                <li>
                    <asp:HyperLink ID="HyperLink1" runat="server">信息中心</asp:HyperLink></li>
                <li>
                    <asp:HyperLink ID="HyperLink2" runat="server" NavigateUrl="~/addBook.aspx">新品上架</asp:HyperLink></li>
                <li>
                    <asp:HyperLink ID="HyperLink3" runat="server">书籍管理</asp:HyperLink></li>
                <li>
                    <asp:HyperLink ID="HyperLink4" runat="server">评论管理</asp:HyperLink></li>
            </ul>
        </nav>
</asp:Content>
<asp:Content ID="Content4" ContentPlaceHolderID="ContentPlaceHolder3" runat="server">
     <div class="mainContainer">
        <h3>用户信息</h3>
         <br />
         <div class="mainGV">
             <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:sqlConnection %>" SelectCommand="SELECT * FROM [Customer]"></asp:SqlDataSource>
             <asp:GridView ID="GridView1" runat="server" AllowPaging="True" AllowSorting="True" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" CellPadding="4" DataKeyNames="Id" DataSourceID="SqlDataSource1" ForeColor="#333333" Height="173px" PageSize="2" Width="535px">
                 <Columns>
                     <asp:BoundField DataField="Id" HeaderText="Id" InsertVisible="False" ReadOnly="True" SortExpression="Id" />
                     <asp:BoundField DataField="Realname" HeaderText="真实姓名" SortExpression="Realname" />
                     <asp:BoundField DataField="LoginName" HeaderText="登录名" SortExpression="LoginName" />
                     <asp:BoundField DataField="Password" HeaderText="密码" SortExpression="Password" />
                     <asp:BoundField DataField="PostCode" HeaderText="邮编" SortExpression="PostCode" />
                     <asp:BoundField DataField="Address" HeaderText="地址" SortExpression="Address" />
                     <asp:BoundField DataField="LinkTel" HeaderText="联系电话" SortExpression="LinkTel" />
                 </Columns>
             </asp:GridView>
         </div>
      </div>
</asp:Content>
<asp:Content ID="Content5" ContentPlaceHolderID="ContentPlaceHolder4" runat="server">
</asp:Content>
<%--<asp:Content ID="Content6" ContentPlaceHolderID="ContentPlaceHolder5" runat="server">
</asp:Content>--%>
